### ISSUE TITLE
Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by liangGeek** [yzydeveloper/fashion-axios#1]
在create-react-app使用时，使用参数装饰器会报错，Module parse failed: Unexpected character '@'，请问什么原因呢

**Comment by yzydeveloper** [comment]
![image](https://github.com/yzydeveloper/fashion-axios/assets/50061726/fdadedba-8392-4496-9d14-0c83c62a661b)


在vscode勾选这两个配置项，或者在ts/jsconfig.json中增加 

```js
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
   }
}
```
